service: koroad-crypt-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: java11
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  memorySize: 512
  timeout: 10
  environment:
    KOROAD_CLIENT_SECRET: ${env:KOROAD_CLIENT_SECRET}

package:
  artifact: build/distributions/koroad-crypt-service.zip

functions:
  crypt:
    handler: com.koroad.crypt.handler.Handler
